version: '3.7'

services:

  ui:
    build:
      context: ./ui
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui/src:/app/src
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    image: pizza-api
    volumes:
      - ./api/dist:/app/dist
      - ./api/contracts:/app/contracts
    ports:
      - 3001:3001
    depends_on:
      - api-watch
    environment:
      WEB3_PROVIDER: 'http://blockchain:8545'
      PORT: 3001
    command: npm run dev

  api-watch:
    image: pizza-api
    command: npm run watch
    volumes:
      - ./api/src:/app/src
      - ./api/dist:/app/dist
    depends_on:
      - truffle

  api-test:
    image: pizza-api
    depends_on:
      - api
    volumes:
      - ./api/dist:/app/dist
      - ./api/test:/app/test
      - ./api/contracts:/app/contracts
    environment:
      API_URL: 'http://api:3001'
    command: npm test

